[package]
name = "sp-consensus"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Common utilities for building and using consensus engines in substrate."
documentation = "https://docs.rs/sp-consensus/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.42"
codec = { package = "parity-scale-codec", version = "2.0.0", features = [
    "derive",
] }
futures = { version = "0.3.1", features = ["thread-pool"] }
log = "0.4.8"
# sp-core = { version = "4.0.0-dev", path = "../../../primitives/core" }
sp-core = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", tag = 'monthly-2021-10' }
sp-inherents = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-state-machine = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
futures-timer = "3.0.1"
sp-std = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-version = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
sp-runtime = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }
thiserror = "1.0.21"

[dev-dependencies]
futures = "0.3.9"
sp-test-primitives = { version = "2.0.0", git = "https://github.com/paritytech/substrate", tag = 'monthly-2021-10' }

[features]
default = []
