[package]
name = "cess-substrate-test-runtime-transaction-pool"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
cess-substrate-test-runtime-client = { version = "2.0.0", path = "../client" }
parking_lot = "0.11.1"
codec = { package = "parity-scale-codec", version = "2.0.0" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", tag = 'monthly-2021-10' }
cessp-runtime = { version = "4.0.0-dev", path = "../../../primitives/runtime" }
sc-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", tag = 'monthly-2021-10', features = ["test-helpers"] }
sc-transaction-pool-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", tag = 'monthly-2021-10' }
futures = "0.3.16"
derive_more = "0.99.2"
